name: unicodeify
version: 1.0.0
build-type: Simple
dependencies:
  - base
  - Cabal
  - haskell-src-exts
  - text
default-extensions:
  - BlockArguments
  - NamedFieldPuns
  - RecordWildCards
  - TupleSections
  - UnicodeSyntax
  - ViewPatterns
ghc-options:
  - -Wall
library:
  source-dirs: src
  exposed-modules:
    - Language.Haskell.Tokens
executable:
  source-dirs:
    - app
    - src
  main: Main.hs
  dependencies:
    - optparse-applicative
    - directory
    - filepath
